name: CatchMate Blue/Green CD

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 가져오기
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # 2. 자바 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create application.yml
        run: |
          mkdir -p ./catchmate-boot/src/main/resources
          cat << 'EOF' > ./catchmate-boot/src/main/resources/application-dev.yml
          ${{ secrets.APPLICATION_YML }}
          EOF
        shell: bash

      - name: Create Firebase Config Directory
        run: |
          mkdir -p ./catchmate-boot/src/main/resources
          cat << 'EOF' | base64 --decode > ./catchmate-boot/src/main/resources/firebase-adminsdk.json
          ${{ secrets.FIREBASE_SERVICE_KEY }}
          EOF
        shell: bash

      # 4. Docker 이미지 빌드 및 업로드 (Push)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/catchmate:latest

      # 5. EC2 접속 및 배포 스크립트 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 프로젝트 폴더로 이동 
            cd /home/ubuntu/catchmatev2-springboot 
            
            git pull origin main
            
            docker-compose up -d nginx
            
            # 실행 권한 재확인
            chmod +x deploy.sh
            
            # 배포 스크립트 실행
            ./deploy.sh
